### ISSUE TITLE
Billboards in pure C++ problem display

### ISSUE THREAD

**Issue by maouache** [wonder-sk/qt3d-experiments#1]
Hi my friend,

I have a problem i try to use your billboard example in my engine, i get both the billboardgeometry.h and billboardgeometry.cpp files and use them in a pure C ++ example without QML and it does not work it show even an error in the shaders "QOpenGLShader :: compile (Fragment): ERROR: 0 :?: 'gl_FragColor': variable is removed in Forward
"
and he displays nothing

is it possible to help me do the same thing but in C ++.

**Comment by wonder-sk** [comment]
Try to have a look at https://github.com/ismailsunni/qt3d-custom-shader - @ismailsunni has ported the QML code to C++ there and later used that code in QGIS (also pure C++) - https://github.com/qgis/QGIS (in src/3d sub-directory)

Hope that helps...

**Comment by maouache** [comment]
that great thank you very much
