### ISSUE TITLE
Translation of billboards example to C++

### ISSUE THREAD

**Issue by florianblume** [wonder-sk/qt3d-experiments#2]
Hi,

I tried to translate your billboards example to C++ [here](https://github.com/florianblume/qt3d-billboards) but got stuck on the geometry renderer. You can find more info in my [stackoverflow question](https://stackoverflow.com/questions/63079722/qt3d-geometry-shader-working-in-qml-but-not-in-c?noredirect=1#comment111551955_63079722).

I'm so intrigued into knowing why it doesn't work and thought that maybe you have an idea :)

**Comment by wonder-sk** [comment]
hi @florianblume 

Actually last year @ismailsunni ported that QML code to C++ for use in QGIS project, with some prototype C++ code here: https://github.com/ismailsunni/qt3d-custom-shader

I have pinged him about your question and he has suggested:

> I suspect it is this one https://github.com/ismailsunni/qt3d-custom-shader/commit/86a0eaf1f41a12bad1f9d636128bf8e4365cc2ee. Because I saw he is using QSize (based on his SO question). We need to use QSizeF instead QSize.

Hopefully that will help :-)

**Comment by florianblume** [comment]
Hey, thanks for your reply! It actually solved my problem!

Thanks again @wonder-sk  and @ismailsunni :)
